global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.yourmailserver.com:587'
  smtp_from: 'alertmanager@yourdomain.com'
  smtp_auth_username: 'alertmanager@yourdomain.com'
  smtp_auth_password: 'yourpassword'

route:
  receiver: 'email-notifications'
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 12h

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'yourteam@yourdomain.com'
        send_resolved: true
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/your/slack/webhook'
        channel: '#alerts'
        send_resolved: true
        title: '{{ .CommonLabels.alertname }} - {{ .CommonLabels.severity }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
          {{ end }}
